# Workflow is called for every pull request regardless which branch its targets
# it runs when a PR is opened, synchronize, reopened or marked ready for review

name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  type-check:
    name: TypeScript check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tsc
        run: pnpm tsc

  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run static checks
        run: pnpm lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unittests
        run: pnpm test