name: Add Tags to Drafts

on:
  project_card:
    types: [created]

jobs:
  add-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add 'technical debt' tag to draft
        if: ${{ github.event.project_card.column_name == 'Technical debt' }}
        run: |
          gh pr create --title "${{ github.event.project_card.note }}" --tag "💸 technical-debt"

      - name: Add 'feature' tag to draft
        if: ${{ github.event.project_card.column_name == 'Features' }}
        run: |
          gh pr create --title "${{ github.event.project_card.note }}" --tag "✨ enhancement"

      - name: Add 'feature' tag to draft
        if: ${{ github.event.project_card.column_name == 'CI/CD processes' }}
        run: |
          gh pr create --title "${{ github.event.project_card.note }}" --tag "🚢 ci/cd"
